### ISSUE TITLE
Cannot reproduce the result of In Shop

### ISSUE THREAD

**Issue by SmithLiu95** [MalongTech/research-xbm#3]
Hi, I am trying to reproduce the result of In shop image retrieval in your paper. However, I only got 0.874 (vs 0.913 in the paper) in terms of recall@1 (which seems to be referred as precision@1 in the code). Attached is my config file, my change of 'trainer.py' (so that it allows to input query and gallery set) and my data preparation code.
[code link here](https://gist.github.com/SmithLiu95/5f5be3da21baf9453c74166b58fafd76)

Thank you very much.

**Comment by bixiaopeng0** [comment]
Hi，Could you reproduce the inshop result?
