### ISSUE TITLE
loss

### ISSUE THREAD

**Issue by bixiaopeng0** [MalongTech/research-xbm#9]
请问你试过softmax+triplet吗，在我代码里没有提升，不知道是啥原因？
我代码里用的 softmax+triplet+xbm(triplet)

**Comment by tim120526** [comment]
什么数据

**Comment by bixiaopeng0** [comment]
已解决，忘记close了。之前打比赛的一些数据。

**Comment by tim120526** [comment]
> 已解决，忘记close了。之前打比赛的一些数据。

请问你 softmax+triplet+xbm(triplet) 最后work吗

**Comment by bixiaopeng0** [comment]
对，有提升。




| |
xiao peng
|
|
***@***.***
|

Signature is customized by Netease Mail Master

On 05/06/2021 15:37, tim20120526 wrote:

已解决，忘记close了。之前打比赛的一些数据。

请问你 softmax+triplet+xbm(triplet) 最后work吗

**Comment by tim120526** [comment]
> 对，有提升。 | | xiao peng | | ***@***.*** | Signature is customized by Netease Mail Master On 05/06/2021 15:37, tim20120526 wrote: 已解决，忘记close了。之前打比赛的一些数据。 请问你 softmax+triplet+xbm(triplet) 最后work吗 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

HI,方便和你请教一些细节吗?可否留个QQ,非常感谢!
